---
- name: Add KeepassXC PPA
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present

- name: Install Keepass
  apt:
    name: keepassxc

# See https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type
- name: Ensure autocomplete will work in Wayland
  lineinfile:
    path: "{{home_folder}}/.profile"
    search_string: "QT_QPA_PLATFORM=xcb"
    line: "export QT_QPA_PLATFORM=xcb"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"