---
- name: Add KeepassXC PPA
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present

- name: Pin repo to ensure things go nice
  copy:
    dest: /etc/apt/preferences.d/keepassxc-pin
    content: |
      Package: keepassxc
      Pin: release l=KeePassXC
      Pin-Priority: 1000

- name: Install Keepass
  apt:
    name: keepassxc

# From https://pled.fr/?p=20783
- name: Install nice decoration for KeepassXC
  apt:
    name: qgnomeplatform-qt5

# We use pam environment to have variables  available to GUI applications (see https://unix.stackexchange.com/a/81274)
- name: Set the required env variable
  lineinfile:
    state: present
    create: true
    path: "{{home_folder}}/.pam_environment"
    search_string: "QT_QPA_PLATFORMTHEME"
    line: "QT_QPA_PLATFORMTHEME='gnome'"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

# See https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type
- name: Ensure autocomplete will work in Wayland
  lineinfile:
    path: "{{home_folder}}/.pam_environment"
    search_string: "QT_QPA_PLATFORM="
    line: "QT_QPA_PLATFORM=xcb"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"