---

# In fact the kdrive version is not even complete, there is some kind of a hash added
# So do a lookup
- name: Check if we should download kDrive
  find: 
    paths: "{{home_folder}}/Applications/"
    file_type: file
    use_regex: yes
    patterns: "kDrive.*AppImage"
  register: kdrive_exists

- name: Download kdrive AppImage
  get_url:
    owner: "{{ansible_user}}"
    url: "https://download.storage.infomaniak.com/drive/desktopclient/kDrive-{{kdrive_version}}-amd64.AppImage"
    dest: "{{download_folder}}"
  when: kdrive_exists.matched == False

# This no more work. I'll have to replace it later
- name: You remember AppImageLauncher prevent kdrive from working ?
  fail:
    msg: We now have to install kDrive in Applications folder. But AppImageLauncher no more works. How to do that?