---
# See https://maniacgeek.net/linux-open-source/comment-installer-vscodium-sur-ubuntu-linux/
- name : Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name : Add Docker apt repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Run the useful docker images
  become: yes
  shell: "{{image_cli}}"
  args:
      executable: /bin/bash
  vars:
    image_cli:
      - docker run -d --name kroki --restart unless-stopped -p29000:8000 yuzutech/kroki
      - docker run -d --name watchtower --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower
#      - docker run -d -p 13000:8080 --add-host=host.docker.internal:host-gateway -v /home/nicolas/.open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
