---
- name: Install git associated packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git

- name: Configure git username globally
  git_config:
    name: user.name
    scope: global
    value: 'Nicolas Delsaux'

- name: Configure git email globally
  git_config:
    name: user.email
    scope: global
    value: 'nicolas.delsaux@gmx.fr'
