---
- name: Install SDK Man
  become: no
  shell: "curl -s 'https://get.sdkman.io' | bash"
  args:
      executable: /bin/bash

- name: Add SDK Man to bash_profile
  become: yes
  become_user: "{{ansible_user}}"
  lineinfile: 
    path: "{{ home }}/.bash_profile"
    line: "{{ item }}"
    state: "present"
    create: "yes"
  with_items:
    - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'

- name: Install Java
  shell: source ~/.bash_profile && sdk install java {{ java_version }}
  args:
    executable: /bin/bash

- name: Install Groovy
  shell: source ~/.bash_profile && sdk install groovy {{groovy_version}}
  args:
    executable: /bin/bash

- name: Install JBang
  shell: source ~/.bash_profile && sdk install jbang
  args:
    executable: /bin/bash

- name: Install Maven
  shell: source ~/.bash_profile && sdk install maven
  args:
    executable: /bin/bash
