---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - cmake
    - make
    - htop
    - bat
    - fzf
    - fonts-firacode

- name: Install and configure git
  include_tasks: git.yml

- name: Install and configure dvc
  include_tasks: dvc.yml

- name: Install Java dependencies
  include_tasks: java.yml

- name: Install Rust dependencies
  include_tasks: rust.yml

- name: Install Eclipse
  flatpak:
    name: org.eclipse.Java

- name: Install some CLI utilities
  include_tasks: cli.yml

- name: Install some editors
  include_tasks: editors.yml

- name: Install Docker containers and other stuff
  include_tasks: docker.yml

# - name: Finally clone some useful repositories
#   include_tasks: clone_my_repositories.yml
