---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - make

- name: Install Java dependencies
  include_tasks: java.yml


- name: Install Codium
  include_tasks: codium.yml

- name: Install Docker containers and other stuff
  include_tasks: docker.yml
