---
- name: Clone open-source repositories
  git:
    repo: git@github.com:Riduidel/{{my_repo_name}}.git
    dest: "{{git_open_source}}/{{my_repo_name}}"
  vars:
    my_repo_name:
      - aadarchi
      - ubuntu-based-laptop
