---
- name: Add Chromium pin
  copy:
    dest: /etc/apt/preferences.d/chromium-pin-deb
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: chromium*
      Pin: release o=LP-PPA-xtradeb-apps
      Pin-Priority: 1000
  register: chromium_pin

- name: Add Chromium snap installation preventer
  copy:
    dest: /etc/apt/preferences.d/chromium-block-snap
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: chromium*
      Pin: release o=Ubuntu
      Pin-Priority: 1
  register: chromium_block

- name: If configuration changed, run apt update
  apt:
    update_cache: true
  when: chromium_pin.changed or chromium_block.changed

# See https://ubuntuhandbook.org/index.php/2021/05/install-chromium-browser-ppa-ubuntu-20-04/
- name: Add Chromium PPA
  apt_repository:
    repo: ppa:xtradeb/apps
    state: present

- name: Remove Chromium snap
  community.general.snap:
    name: chromium
    state: absent

- name: Install Chromium
  apt:
    name: chromium

- name: Change global chromium configuration to have the google photo usable in profile
  copy:
    dest: /etc/chromium-browser/default
    # See https://stackoverflow.com/a/67459416/15619
    content: |
      CHROMIUM_FLAGS="--oauth2-client-id=77185425430.apps.googleusercontent.com --oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT" 
  register: chromium_pin
