---
- name: Add Mozilla repository signature
# See https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
  apt_key:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg 

- name : Add Mozilla apt repo
  apt_repository:
    repo: deb https://packages.mozilla.org/apt mozilla main
    state: present

- name: Add Firefox pin
  copy:
    dest: /etc/apt/preferences.d/firefox-pin-deb
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: firefox*
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
  register: firefox_pin

- name: Add firefox snap installation preventer
  copy:
    dest: /etc/apt/preferences.d/firefox-block-snap
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: firefox*
      Pin: release o=Ubuntu
      Pin-Priority: -1
  register: firefox_block

- name: Update apt cache if configuration changed
  apt:
    update_cache: true
  when: firefox_pin.changed or firefox_block.changed

- name: Remove Firefox snap
  community.general.snap:
    name: firefox
    state: absent

- name: Install Firefox from .deb
  apt:
    name: "{{item}}"
  with_items: 
    - firefox
    - firefox-l10n-fr