---
# See https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
- name: Add Mozilla team PPA
  deb822_repository:
    name: Mozillateam
    state: present
    uris: https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/
    suites: plucky
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x738beb9321d1aaec13ea9391aebdf4819be21867
    components:
      - main
  register: firefox_ppa

- name: Add Firefox pin
  copy:
    dest: /etc/apt/preferences.d/firefox-pin-deb
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: firefox*
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
  register: firefox_pin

- name: Add firefox snap installation preventer
  copy:
    dest: /etc/apt/preferences.d/firefox-block-snap
    # We prefer all packgaes from mozilla, hopping they do good
    content: |
      Package: firefox*
      Pin: release o=Ubuntu
      Pin-Priority: -1
  register: firefox_block

- name: Update apt cache if configuration changed
  apt:
    update_cache: true
  when: firefox_ppa.changed or firefox_pin.changed or firefox_block.changed

- name: Remove Firefox snap
  community.general.snap:
    name: firefox
    state: absent

- name: Install Firefox from .deb
  apt:
    name: "{{item}}"
    allow_downgrade: true
  with_items: 
    - firefox
    - firefox-locale-fr

- name: Add option to allow Firefox to use touchpad gestures
  become: true
  become_user: "{{ansible_user}}"
  lineinfile: 
    path: "{{ home }}/.bash_profile"
    line: "{{ item }}"
    state: "present"
    create: "yes"
  with_items:
    - 'export MOZ_ENABLE_WAYLAND=1'

