---
- name: Install Gnome tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweaks
    - gnome-shell-extension-manager
#    - gconf2

# Changed settings were found thanks to this trick https://discourse.gnome.org/t/gsettings-monitor-all-system-settings-change/3699
# Unfortunatly the ansible role doesn't work (since gconftool2 is deprecated)
#- name: Set night mode on
#  community.general.gconftool2:
#    state: present
#    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
#    value: "true"
#    value_type: "bool"
#
#- name: Show battery level
#        key: "/org/gnome/desktop/interface/show-battery-percentage"
#        value: true
#        type: "bool"
#      no_dynamic_workspaces:
#        key: "/org/gnome/mutter/dynamic-workspaces"
#        value: false
#        type: "bool"
#      only_one_workspace:
#        key: /org/gnome/desktop/wm/preferences/num-workspaces
#        value: 1
#        type: "int"
#      "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding": '<Control><Alt>v'
#      "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command": '/usr/bin/diodon'
#      "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name": 'trigger diodon'
#
#      # Finally set list of shortcuts

- name: Install Pano requirements
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gir1.2-gda-5.0
    - gir1.2-gsound-1.0

- name: Install gnome-extensions command line
  become: true
  become_user: "{{ansible_user}}"
  command: pipx install gnome-extensions-cli

- name: Install Gnome extensions
  become: true
  become_user: "{{ansible_user}}"
  command: "./gnome-extensions-cli install {{item}}"
  args:
    chdir: "{{local_bin_folder}}"
  with_items:
    - 3628 #arcmenu/
    - 1160 #dash-to-panel/
    - 6096 #smile-complementary-extension/
    - 7065 #tiling-shell/
    - 4470 #media-controls/
    - 3843 #just-perfection/
    - 19 #user-themes/
    - 6784 #wiggle/
    - 5724 # battery health charging
    - 6670 # bluetooth battery meter
    - 6922 # Gravatar
