---
- name: Install Gnome tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweaks
    - gnome-shell-extension-manager
#    - gconf2

- name: Install gnome-extensions command line
  become: true
  become_user: "{{ansible_user}}"
  command: pipx install gnome-extensions-cli

# Quite sure there is a better way to do that
- name: Install Gnome extensions
  become: true
  become_user: "{{ansible_user}}"
  command: "./gnome-extensions-cli install {{item}}"
  args:
    chdir: "{{local_bin_folder}}"
  with_items:
    - 3628 #arcmenu/
    - 1160 #dash-to-panel/
    - 6096 #smile-complementary-extension/
    - 7065 #tiling-shell/
    - 4470 #media-controls/
    - 3843 #just-perfection/
    - 19 #user-themes/
    - 6784 # wiggle/
    - 5724 # battery health charging
    - 6670 # bluetooth battery meter
    - 6922 # Gravatar
    - 8834 # Copyons
