---
- name: Install Gnome tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweaks
    - gnome-shell-extension-manager
#    - gconf2

- name: Install gnome-extensions command line
  become: true
  become_user: "{{ansible_user}}"
  command: pipx install gnome-extensions-cli

- name: Install pykeepass
  ansible.builtin.pip: 
    name: pykeepass
  delegate_to: localhost 

# Quite sure there is a better way to do that
- name: Install Gnome extensions
  become: true
  become_user: "{{ansible_user}}"
  command: "./gnome-extensions-cli install {{item}}"
  args:
    chdir: "{{local_bin_folder}}"
  with_items:
    - 3628 #arcmenu/
    - 1160 #dash-to-panel/
    - 7065 #tiling-shell/
    - 4470 #media-controls/
    - 3843 #just-perfection/
    - 19 #user-themes/
    - 6784 # wiggle/
    - 6670 # bluetooth battery meter
    - 6922 # Gravatar
    - 8834 # Copyons
    - 8671 # All in one clipboard
    - 8323 # Gnoming profiles

- name: Configure gnoming-profiles
  become: true
  become_user: "{{ansible_user}}"
  command: "gsettings --schemadir {{gnoming_profiles_schema_dir}} set {{gnoming_profiles_schema}} {{ item.key }} {{ item.value }}"
  loop: "{{ gnoming_profiles_config|dict2items }}"

- name: Don't forget to set github token
  debug:
    msg: "gsettings --schemadir {{gnoming_profiles_schema_dir}} set {{gnoming_profiles_schema}} github-token $GITHUB_TOKEN"
 