---
- name: Install Pano requirements
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gir1.2-gda-5.0
    - gir1.2-gsound-1.0

- name: Install gnome-extensions command line
  become: yes
  become_user: "{{ansible_user}}"
  command: pipx install gnome-extensions-cli

- name: Install Gnome extensions
  become: yes
  become_user: "{{ansible_user}}"
  command: "gnome-extensions-cli install {{item}}"
  args:
    chdir: "{{home_folder}}/.local/bin"
  with_items:
    - 7065 #tiling-shell/
    - 4470 #media-controls/
    - 4245 #gesture-improvements/
    - 5278 #pano/
    - 1160 #dash-to-panel/
    - 3628 #arcmenu/
    - 6096 #smile-complementary-extension/
    - 3193 #blur-my-shell/
    - 3843 #just-perfection/
    - 19 #user-themes/
