---
- name: Install easy packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweaks
    - gnome-shell-extension-manager
    - flameshot
    - timeshift
- name: Install Droidcam
  include_tasks: droidcam.yml


- name: Install Chromium
  include_tasks: chromium.yml

#- name: Install Pano
#  include_tasks: pano.yml

#- name: Install Stacer
#  include_tasks: stacer.yml

#- name: Install Mission Center
#  include_tasks: mission_center.yml

- name: Install Touchegg
  include_tasks: touchegg.yml