---
- name: Install easy packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweaks
    - gnome-shell-extension-manager
    - flameshot
    - timeshift
    - filezilla
    - dirmngr
    - gnupg
    - apt-transport-https
    - ca-certificates
    - flatpak
    - gnome-software-plugin-flatpak
    - python3-pip
    - pipx
    # THis clupboard manager seems to work quite well with Wayland
    - diodon
    - redshift-gtk
    - tilix

- name: Install flatpak
  include_tasks: flatpak.yml

- name: Install Touchegg
  include_tasks: touchegg.yml

- name: Install Droidcam
  include_tasks: droidcam.yml

- name: Install Chromium
  include_tasks: chromium.yml

#- name: Install Stacer
#  include_tasks: stacer.yml

- name: Install Lutris
  include_tasks: lutris.yml

# - name: Install gnome extensions
#   include_tasks: gnome_extensions.yml

# TODO Automate dynamic wallpapers install (but it never worked https://github.com/saint-13/Linux_Dynamic_Wallpapers)
