---
- name: Install Python packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pip
      - python3-venv
      - pipx

# https://stackoverflow.com/a/43108253/15619
# DAAAMN https://github.com/Bigouden/woob-bank-exporter
