---
- name: Install Python packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pip
      - pipx

- name: Make sure pipx works
  lineinfile: 
    path: "{{ home }}/.bashrc"
    line: "export PATH=\"$PATH:{{home_folder}}/.local/bin\""
    state: "present"
    create: "yes"
