---
- name: Install Thunderbird required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - thunderbird
    - thunderbird-locale-fr

# - name: Copy autoexec file in the right location
#   template:
#     src: autoconfig.js
#     dest: /usr/lib/thunderbird/defaults/pref/
#     owner: root
#     group: root

# - name: Copy thunderbird.cfg in the right location
#   template:
#     src: thunderbird.json.jinja
#     dest: /usr/lib/thunderbird/thunderbird.cfg
#     owner: root
#     group: root
